#!/usr/bin/env python3
from __future__ import annotations

import os
import re
import shutil
from pathlib import Path

# docs/source/api
API_DIR = Path(__file__).resolve().parent / "source" / "api"

PACKAGE = "fast_lisa_subtraction"
PREFIX = PACKAGE + "."

# Files generated by sphinx-apidoc that we don't want as entry points
DROP_FILES = {"modules.rst"}  # we will remove it
KEEP_TOPLEVEL = {"index.rst"}  # keep our API root


def _ensure_dir(p: Path) -> None:
    """Ensure a directory exists.

    Parameters
    ----------
    p : pathlib.Path
        Directory path to create if missing.

    Returns
    -------
    None
    """
    p.mkdir(parents=True, exist_ok=True)


def _write_api_root_index() -> None:
    """Write the API root index page.

    Returns
    -------
    None
    """
    idx = API_DIR / "index.rst"
    txt = """Fast Lisa Subtraction API
=========================

.. toctree::
   :maxdepth: 2

   priors/index
   simulation/index
   utils/index
"""
    idx.write_text(txt, encoding="utf-8")


def _slug_title(name: str) -> str:
    """Return a display title for a section.

    Parameters
    ----------
    name : str
        Section name.

    Returns
    -------
    str
        Title string.
    """
    # title shown in rst page; keep it simple
    return name


def organize_api_files() -> None:
    """Reorganize Sphinx API files into subpackage folders.

    Files generated by ``sphinx-apidoc`` are moved from flat module names
    (e.g., ``fast_lisa_subtraction.priors.analytical.rst``) into subpackage
    folders (e.g., ``priors/analytical.rst``). Package stubs are kept at
    the top level and their toctrees are fixed later.

    Returns
    -------
    None

    Raises
    ------
    RuntimeError
        If the API output directory does not exist.
    """
    if not API_DIR.exists():
        raise RuntimeError(f"API_DIR does not exist: {API_DIR}")

    # Remove unwanted generated files (e.g. modules.rst)
    for d in DROP_FILES:
        p = API_DIR / d
        if p.exists():
            p.unlink()

    for p in list(API_DIR.glob("*.rst")):
        fn = p.name

        if fn in KEEP_TOPLEVEL:
            continue

        # Only move "fast_lisa_subtraction.<something>.rst"
        if not fn.startswith(PREFIX) or not fn.endswith(".rst"):
            continue

        mod = fn[len(PREFIX):-4]  # strip prefix and .rst
        parts = mod.split(".") if mod else []

        # If it's exactly the package root file "fast_lisa_subtraction.rst", keep it top-level.
        # (That's generated as fast_lisa_subtraction.rst, NOT prefixed; but keep this anyway.)
        if not parts:
            continue

        # If it's a subpackage stub like "priors.rst" (from fast_lisa_subtraction.priors.rst),
        # keep at top-level as "priors.rst"
        if len(parts) == 1:
            # Rename to priors.rst / simulation.rst / utils.rst
            dst = API_DIR / f"{parts[0]}.rst"
            if dst.exists():
                dst.unlink()
            p.rename(dst)
            continue

        # Otherwise it's a module under a subpackage: move into folder(s)
        subdir = API_DIR / parts[0]  # priors / simulation / utils
        _ensure_dir(subdir)
        new_name = parts[-1] + ".rst"
        dst = subdir / new_name
        if dst.exists():
            dst.unlink()
        shutil.move(str(p), str(dst))


def _fix_toctree_paths_in_package_stub(stub_path: Path, section: str) -> None:
    """Fix toctree paths in a subpackage stub file.

    Parameters
    ----------
    stub_path : pathlib.Path
        Path to the stub file (e.g., ``priors.rst``).
    section : str
        Subpackage name (e.g., ``"priors"``).

    Returns
    -------
    None
    """
    if not stub_path.exists():
        return

    lines = stub_path.read_text(encoding="utf-8").splitlines(True)
    out: list[str] = []

    # Pattern matching sphinx-apidoc's docnames inside toctree
    # e.g. "   api/fast_lisa_subtraction.priors.analytical"
    # or sometimes "   fast_lisa_subtraction.priors.analytical"
    pat = re.compile(r"^(\s+)(?:api/)?fast_lisa_subtraction\." + re.escape(section) + r"\.([A-Za-z0-9_]+)\s*$")

    for line in lines:
        m = pat.match(line)
        if m:
            indent, modname = m.group(1), m.group(2)
            out.append(f"{indent}{section}/{modname}\n")
        else:
            out.append(line)

    stub_path.write_text("".join(out), encoding="utf-8")


def _write_subpackage_index(section: str) -> None:
    """Create a subpackage index listing local ``.rst`` files.

    Parameters
    ----------
    section : str
        Subpackage name (e.g., ``"priors"``).

    Returns
    -------
    None
    """
    sec_dir = API_DIR / section
    _ensure_dir(sec_dir)

    entries = []
    for p in sorted(sec_dir.glob("*.rst")):
        if p.name == "index.rst":
            continue
        entries.append(p.stem)

    title = _slug_title(section)
    txt = [f"{title}\n" + "=" * len(title) + "\n\n",
           ".. toctree::\n",
           "   :maxdepth: 2\n\n"]
    for e in entries:
        txt.append(f"   {e}\n")

    (sec_dir / "index.rst").write_text("".join(txt), encoding="utf-8")


def _ensure_root_package_page_not_in_api_root() -> None:
    """Rewrite the root package page to avoid duplicate toctrees.

    Returns
    -------
    None
    """
    root = API_DIR / f"{PACKAGE}.rst"
    if not root.exists():
        return

    # Replace any existing toctree with a short page that just documents the package,
    # without linking priors/simulation/utils (api/index does that).
    txt = f"""{PACKAGE}
{'=' * len(PACKAGE)}

.. automodule:: {PACKAGE}
   :members:
   :undoc-members:
   :show-inheritance:
"""
    root.write_text(txt, encoding="utf-8")


def main() -> None:
    """Run the API file organization workflow.

    Returns
    -------
    None
    """
    organize_api_files()

    # Rewrite API root index (Option B)
    _write_api_root_index()

    # Fix package stub toctrees (these are the ones currently warning)
    for section in ("priors", "simulation", "utils"):
        _fix_toctree_paths_in_package_stub(API_DIR / f"{section}.rst", section)
        _write_subpackage_index(section)

    # Ensure root package page doesn't create duplicate navigation
    _ensure_root_package_page_not_in_api_root()

    print("API organization done.")
    print(f"API root: {API_DIR / 'index.rst'}")


if __name__ == "__main__":
    main()
